export default {
  rules: {
    "compatible-pragma": "error",
    "curly": "off",
    "explicit-types": "off",
    "id-denylist": "off",
    "imports-on-top": "error",
    "max-state-vars": "off",
    "named-return-params": "off",
    "naming-convention": "off",
    "no-console": "error",
    "no-default-visibility": "off",
    "no-duplicate-imports": "error",
    "no-empty-blocks": "off",
    "no-global-imports": "off",
    "no-hardcoded-gas": "off",
    "no-restricted-syntax": "off",
    "no-send": "off",
    "no-tx-origin": "off",
    "no-unchecked-calls": "error",
    "no-uninitialized-immutable-references": "error",
    "no-unnecessary-boolean-compare": "off",
    "no-unnecessary-else": "off",
    "no-unused-vars": "error",
    "one-contract-per-file": "off",
    "private-vars": "off",
    "require-revert-reason": "off",
    "sort-imports": "off",
    "sort-members": "off",
    "sort-modifiers": "off",
    "yul-prefer-iszero": "error",
  },
};