// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import 'hardhat/types/artifacts'

import { LegacyETHRegistrarController$Type } from './LegacyETHRegistrarController'
import { LegacyPublicResolver$Type } from './LegacyPublicResolver'

declare module 'hardhat/types/artifacts' {
  interface ArtifactsMap {
    ['LegacyETHRegistrarController']: LegacyETHRegistrarController$Type
    ['LegacyPublicResolver']: LegacyPublicResolver$Type
  }

  interface ContractTypesMap {
    ['LegacyETHRegistrarController']: GetContractReturnType<
      LegacyETHRegistrarController$Type['abi']
    >
    ['LegacyPublicResolver']: GetContractReturnType<LegacyPublicResolver$Type['abi']>
  }
}
