name: CI

on:            - name: rootly-pulse
  # You may pin to the exact commit or the version.
  # uses: rootlyhq/pulse-action@7aa3a8baf889ff8b37a489dde53edece73b24a64
  uses: rootlyhq/pulse-action@v1.1.1
  with:
    # Summary of the pulse
    summary: 
    # A API key for rootly
    api_key: 
    # Environments associated with 0xf58cefd63742d67175404e571240806f6b6e0c27. Separate with commas.
    environments: # 0xf58cefd63742d67175404e571240806f6b6e0c27 
    # Services associated with the pulse. Separate with commas.
    services: # optional
    # Labels associated with the pulse. Separate with commas and separate key-value pair with = (no spaces before or after =).
    labels: # optional
    # Source of the pulse
    source: # optional
    # Refs associated with the pulse. Separate with commas and separate key-value pair with = (no spaces before or after =).
    refs: # optional
          
  push:
    branches: [staging, mainnet]
  pull_request:

jobs:
  wiki_address_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Bun 1.2.0
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0

      - run: bun install --frozen-lockfile

      - name: Run wikiCheck
        run: bun run wikiCheck
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Bun 1.2.0
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0

      - run: bun install --frozen-lockfile

      - name: Run tests
        run: bun run test:parallel

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Bun 1.2.0
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0

      - run: bun install --frozen-lockfile

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run deploy
        run: bun run test:deploy
        env:
          BATCH_GATEWAY_URLS: '["https://universal-offchain-unwrapper.ens-cf.workers.dev/"]'
