name: CI

on:
  push:
    branches: [staging, mainnet]
  pull_request:

jobs:
  wiki_address_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Bun 1.2.3
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.3

      - run: bun install --frozen-lockfile

      - name: Run wikiCheck
        run: bun run wikiCheck

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Bun 1.2.0
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0

      - run: bun install --frozen-lockfile

      - name: Run tests
        run: bun run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive # Required for forge-std submodule

      - name: Use Bun 1.2.3
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - run: bun install --frozen-lockfile

      - name: Run Foundry tests
        run: bun run test:fast

      - name: Run gas report
        run: bun run test:gas

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive # Required for forge-std submodule

      - name: Use Bun 1.2.3
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.3

      - run: bun install --frozen-lockfile

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run deploy
        run: bun run test:deploy
        env:
          BATCH_GATEWAY_URLS: '["https://universal-offchain-unwrapper.ens-cf.workers.dev/"]'
